// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_address_data`, `calculate_checksum`, `generate_keypair_from_seed`, `generate_seed`, `get_public_key`, `hash_public_key`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 为Flutter暴露的API函数
/// 生成新的用户身份标识
UserIdentity generateUserIdentity() =>
    RustLib.instance.api.crateApiUserIdentityGenerateUserIdentity();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UserIdentity>>
abstract class UserIdentity implements RustOpaqueInterface {
  String get address;

  String get privateKey;

  String get publicKey;

  set address(String address);

  set privateKey(String privateKey);

  set publicKey(String publicKey);

  /// 生成完整的用户身份标识
  static Future<UserIdentity> generateIdentity() =>
      RustLib.instance.api.crateApiUserIdentityUserIdentityGenerateIdentity();
}
